make: myshell islem topla tekrar cikar clear

myshell: myshell.c
	 gcc myshell.c -o myshell

islem: islem.c 
	gcc islem.c -o islem

topla: topla.c 
	gcc topla.c -o topla

tekrar: tekrar.c 
	gcc tekrar.c -o tekrar 

cikar: cikar.c 
	gcc cikar.c -o cikar

clear: 
	rm -rf *o shell